### topology
n_stacks: 1
n_skips: 1
max_n_frames: 1600
conv_in_channel: 1
conv_channels: "32_32"
conv_kernel_sizes: "(3,3)_(3,3)"
conv_strides: "(1,1)_(1,1)"
conv_poolings: "(2,2)_(2,2)"
conv_batch_norm: false
conv_layer_norm: false
enc_type: conv_conformer
enc_n_layers: 6
transformer_enc_pe_type: none  ###
lc_chunk_size_left: 64
lc_chunk_size_current: 64
lc_chunk_size_right: 32
lc_type: reshape
transformer_enc_d_model: 256
transformer_enc_d_ff: 2048
transformer_enc_n_heads: 4
dec_type: lstm_transducer
dec_n_units: 1024
dec_n_projs: 0
dec_n_layers: 2
dec_bottleneck_dim: 512
emb_dim: 512
tie_embedding: false
### optimization
batch_size: 8
optimizer: noam
n_epochs: 40
convert_to_sgd_epoch: 100
print_step: 2000  # 1000->4000
metric: edit_distance
lr_factor: 5.0
early_stop_patient_n_epochs: 5
shuffle_bucket: true  ### this is important
sort_stop_epoch: 100
eval_start_epoch: 1
warmup_n_steps: 25000
accum_grad_n_steps: 32  ### 8*4
### initialization
param_init: 0.1
### regularization
clip_grad_norm: 5.0
dropout_in: 0.1
dropout_enc: 0.1
dropout_dec: 0.1
dropout_emb: 0.1
dropout_att: 0.1
weight_decay: 1e-6
### MTL
ctc_weight: 0
mtl_per_batch: false
task_specific_layer: false
